### ISSUE TITLE
Crash with Quark

### ISSUE THREAD

**Issue by Pentasis** [Pyre540/spawn-preventing-beacon#1]
When quark is installed I get a crash; here's the crash-log: https://paste.dimdev.org/ipopuyaqej.mccrash

(EDIT: I know the log states the crash is caused by Quark, but removing your mod solves the issue and the log talks about BeaconReplacementHandler, hence my suspicion it is your mod that causes it)

**Comment by Pyre540** [comment]
From what I see in the code Quark blindly assumes the number of effects in vanilla beacon and iterates over them. In my mod I injected there additional one, so Quark crashes because of that (Caused by: java.lang.ArrayIndexOutOfBoundsException: 2).
I may try to deley effect injetion in my mod so Quark can copy effects safely but I don't know what Quark is trying to do with beacon so it is hard to tell if it is the only issue.

**Comment by Pentasis** [comment]
You want me to make an Issue/cross-post on Quark's github?

**Comment by Pyre540** [comment]
Sure, go ahead :)
In the meantime, when I have a free moment, I will try to solve it on my side.

**Comment by EvertX** [comment]
Seems it was solved on Quark's side.

**Comment by Pentasis** [comment]
Nope, seems the fix on quark's side didn't work: https://paste.dimdev.org/izewusigis.mccrash

**Comment by Pyre540** [comment]
Should be fixed in next Quark version :)
https://github.com/Vazkii/Quark/commit/13f297887c6c5182d95975ebbc7abbb9fe7dd876
